name: Auto-Update AdGuard Rules
on:
  # 1. 监听目标仓库的更新（通过手动触发或定时检查）
  workflow_dispatch:  # 手动触发按钮
  schedule:
    - cron: "0 */6 * * *"  # 每6小时检查一次源文件更新[2](@ref)
  # 2. 监听规则文件本身的更新（避免循环触发）
  push:
    paths:
      - "adguard-rules.txt"  # 排除自身修改的触发[5,7](@ref)

jobs:
  process-rules:
    runs-on: ubuntu-latest
    steps:
      # 步骤1: 检出当前仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史[1](@ref)

      # 步骤2: 下载源文件并检查更新
      - name: Download and compare rules
        run: |
          # 下载最新源文件
          curl -sSfL -o latest.txt https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/pihole.txt
          
          # 若文件无变化则跳过后续步骤
          if cmp -s latest.txt raw.txt; then
            echo "源文件未更新，任务终止"
            exit 0
          fi

      # 步骤3: 处理规则格式
      - name: Format rules
        run: |
          sed -e 's/^/||/' -e 's/$/^/' latest.txt > adguard-rules.txt
          # 可选：去重处理
          sort -u adguard-rules.txt -o adguard-rules.txt

      # 步骤4: 自动提交更新
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update AdGuard rules from source"
          file_pattern: adguard-rules.txt
          branch: main  # 目标分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
