name: Auto-Update AdGuard Rules
on:
  workflow_dispatch:  
  schedule:
    - cron: "0 */6 * * *" 
  push:
    paths:
      - "adguard-rules.txt"  

jobs:
  process-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Download and compare rules
        run: |
          curl -sSfL -o latest.txt https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/pihole.txt
          
          if cmp -s latest.txt raw.txt; then
            echo "源文件未更新，任务终止"
            exit 0
          fi

      - name: Format rules
        run: |
          grep -v "^#" latest.txt | sed -e 's/^/||/' -e 's/$/^/' > adguard-rules.txt

          sort -u adguard-rules.txt -o adguard-rules.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update AdGuard rules from source"
          file_pattern: adguard-rules.txt
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
